# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0634ad6a5e042cd50fd8cd197f216f2763c004d1de16d5e03b84ce53181bef9cbd4f5f7aec051ccc9c024a720e451d015c9fe9b35a4444846c38df9be4fd544

test:
  secret_key_base: 0ca0e233f4ba080c7ea419874bc6fc15f335676873ea39ac313b5709bde7f6b25d044fb324886babfab10f5c6cd9de57a73b5082228566e8f20a78dddeba0365

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
